name: Issue
description: 기능 개발, 버그 수정, 리팩토링 등 이슈 생성
title: "[ ] "
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 개요
        이슈에서 무엇을 구현/수정하는지 간단히 작성해 주세요.

  - type: textarea
    id: overview
    attributes:
      label: 개요
      placeholder: |
        예)
        - 기능 생성 및 삭제 구현
        - 기존 생성 로직 개선
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 상세 구현 계획 및 체크리스트
        작업 단위를 기준으로 자유롭게 작성해 주세요.

  - type: textarea
    id: plan
    attributes:
      label: 구현 계획
      placeholder: |
        ### 1. 소제목1
        - [ ] 내용1
        - [ ] 내용2

        ### 2. 소제목2
        - [ ] 내용1
        - [ ] 내용2
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 참고 사항 / 후속 작업
      placeholder: |
        예)
        - 생성 기능 구현 후 테스트 코드 병합 예정
        - 서버 응답 속도에 따라 로딩 상태 추가 검토
